version: "3.1"
services:
  redis:
    image: redis:7-alpine
    ports: 
      - 6379:6379
    volumes:
      - redis-data:/data
  mongodb:
    image: mongo:5.0.9
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27018:8081
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local
  redis-data:
    driver: local
